services:
    _defaults:
        autoconfigure: true
        autowire: false

    Terminal42\Geoip2CountryBundle\Backend\CountryPreviewModule:
        arguments:
            - '@request_stack'
            - '@translator'
            - '@contao.intl.countries'
            - '@contao.csrf.token_manager'
        public: true

    Terminal42\Geoip2CountryBundle\CountryProvider:
        arguments:
            - ~
            - '%terminal42_geoip2_country.fallback_country%'
        tags:
            - { name: kernel.reset, method: reset }

    Terminal42\Geoip2CountryBundle\EventListener\FormCountrySelectListener:
        arguments:
            - '@Terminal42\Geoip2CountryBundle\CountryProvider'
            - '@request_stack'
        tags:
            - { name: contao.hook, hook: loadFormField }

    Terminal42\Geoip2CountryBundle\EventListener\KernelResponseListener:
        arguments:
            - '@Terminal42\Geoip2CountryBundle\CountryProvider'
        tags:
            - { name: kernel.event_listener }

    Terminal42\Geoip2CountryBundle\EventListener\DcaLoaderListener:
        arguments:
            - '@database_connection'
            - '@translator'
            - '@contao.intl.countries'
            - '%terminal42_geoip2_country.dca_tables%'
        tags:
            - { name: contao.hook, hook: loadDataContainer }

    Terminal42\Geoip2CountryBundle\EventListener\MemberCountryListener:
        arguments:
            - '@Terminal42\Geoip2CountryBundle\CountryProvider'
            - '@request_stack'
        tags:
            - { name: contao.hook, hook: loadDataContainer }

    Terminal42\Geoip2CountryBundle\EventListener\NavigationTemplateListener:
        arguments:
            - '@Terminal42\Geoip2CountryBundle\CountryProvider'
            - '@request_stack'
        tags:
            - { name: contao.hook, hook: parseTemplate }

    Terminal42\Geoip2CountryBundle\EventListener\PageRoutingDataContainerListener:
        arguments:
            - '@database_connection'
            - '@contao.intl.countries'
            - '@translator'
            - '@security.authorization_checker'
        tags:
            - { name: contao.callback, table: tl_page, target: config.onload, method: addGlobalOperation }
            - { name: contao.callback, table: tl_page_geoip, target: list.label.label, method: generateLabel }
            - { name: contao.callback, table: tl_page_geoip, target: fields.country.options, method: getCountryOptions }
            - { name: contao.callback, table: tl_page_geoip, target: fields.pages.options, method: getPagesOptions }

    Terminal42\Geoip2CountryBundle\EventListener\VisibleElementListener:
        arguments:
            - '@Terminal42\Geoip2CountryBundle\CountryProvider'
            - '@request_stack'
            - '@contao.routing.scope_matcher'
        tags:
            - { name: contao.hook, hook: isVisibleElement }

    Terminal42\Geoip2CountryBundle\Migration\UppercaseCountryMigration:
        arguments:
            - '@database_connection'
            - '%terminal42_geoip2_country.dca_tables%'
        tags:
            - contao.migration

    Terminal42\Geoip2CountryBundle\Routing\CountryRestrictionFilter:
        arguments:
            - '@Terminal42\Geoip2CountryBundle\CountryProvider'

    Terminal42\Geoip2CountryBundle\Routing\CountryRoutingFilter:
        arguments:
            - '@database_connection'
            - '@Terminal42\Geoip2CountryBundle\CountryProvider'
