services:
    _defaults:
        autoconfigure: true
        autowire: false

    Terminal42\Geoip2CountryBundle\Backend\CountryPreviewModule:
        arguments:
            - '@database_connection'
            - '@request_stack'
            - '@translator'
            - '%terminal42_geoip2_country.dca_tables%'
        public: true

    Terminal42\Geoip2CountryBundle\CountryProvider:
        arguments:
            - ~
            - '%terminal42_geoip2_country.fallback_country%'

    Terminal42\Geoip2CountryBundle\EventListener\FormCountrySelectListener:
        arguments:
            - '@Terminal42\Geoip2CountryBundle\CountryProvider'
            - '@request_stack'
        tags:
            - { name: contao.hook, hook: loadFormField }

    Terminal42\Geoip2CountryBundle\EventListener\KernelResponseListener:
        arguments:
            - '@Terminal42\Geoip2CountryBundle\CountryProvider'
        tags:
            - { name: kernel.event_listener }

    Terminal42\Geoip2CountryBundle\EventListener\DcaLoaderListener:
        arguments:
            - '@database_connection'
            - '@translator'
            - '%terminal42_geoip2_country.dca_tables%'
        tags:
            - { name: contao.hook, hook: loadDataContainer }

    Terminal42\Geoip2CountryBundle\EventListener\MemberCountryListener:
        arguments:
            - '@Terminal42\Geoip2CountryBundle\CountryProvider'
            - '@request_stack'
        tags:
            - { name: contao.hook, hook: loadDataContainer }

    Terminal42\Geoip2CountryBundle\EventListener\NavigationTemplateListener:
        arguments:
            - '@Terminal42\Geoip2CountryBundle\CountryProvider'
            - '@request_stack'
        tags:
            - { name: contao.hook, hook: parseTemplate }

    Terminal42\Geoip2CountryBundle\EventListener\VisibleElementListener:
        arguments:
            - '@Terminal42\Geoip2CountryBundle\CountryProvider'
            - '@request_stack'
        tags:
            - { name: contao.hook, hook: isVisibleElement }

    Terminal42\Geoip2CountryBundle\Routing\CountryRestrictionFilter:
        arguments:
            - '@Terminal42\Geoip2CountryBundle\CountryProvider'
